# Generated by Django 4.2.1 on 2023-05-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rareuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
